{{- $root := . }}

{{- $ixia_default_img1 := "ghcr.io/open-traffic-generator/keng-controller:latest" }}
{{- $ixia_default_img2 := "ghcr.io/open-traffic-generator/otg-gnmi-server:latest" }}
{{- $ixia_default_memory := "25Mi" }}
{{- $ixia_default_cpu := "10m" }}

{{- range $i, $ := .Values.topology.nodes }}
{{- if eq .type "ixia-c" }}
---
apiVersion: v1
kind: Pod
metadata:
  name: otg-controller
  annotations:
    v1.multus-cni.io/default-network: {{ $root.Values.default_network.name }}
  labels:
    app: ixia-c
    role: controller
{{ include "netclab.labels" $root | indent 4 }}
spec:
  containers:
    - name: otg-controller
      image: {{ default $ixia_default_img1 .image1 }}
      args:
        - --accept-eula
        - --debug
      volumeMounts:
        - mountPath: /home/ixia-c/controller/config
          name: config
          readOnly: true
      resources:
        requests:
          cpu: {{ default $ixia_default_cpu .cpu }}
          memory: {{ default $ixia_default_memory .memory }}
    - name: otg-gnmi-server
      image: {{ default $ixia_default_img2 .image2 }}
      args:
        - -http-server
        - https://localhost:8443
        - --debug
      ports:
        - containerPort: 50051
          name: gnmi-port
          protocol: TCP
      resources:
        requests:
          cpu: {{ default $ixia_default_cpu .cpu }}
          memory: {{ default $ixia_default_memory .memory }}
  restartPolicy: Always
  volumes:
    - configMap:
        defaultMode: 420
        name: otg-controller-config
      name: config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otg-controller-config
  labels:
    app: ixia-c
{{ include "netclab.labels" $root | indent 4 }}
data:
  config.yaml: |
    location_map:
    - location: eth1
      endpoint: otg-port-1.default.svc.cluster.local:5555+otg-port-1.default.svc.cluster.local:50071
    - location: eth2
      endpoint: otg-port-2.default.svc.cluster.local:5555+otg-port-2.default.svc.cluster.local:50071
    - location: eth3
      endpoint: otg-port-3.default.svc.cluster.local:5555+otg-port-3.default.svc.cluster.local:50071
---
apiVersion: v1
kind: Service
metadata:
  name: otg-controller-svc
  labels:
    app: ixia-c
{{ include "netclab.labels" $root | indent 4 }}
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: grpc
      port: 40051
      protocol: TCP
      targetPort: 40051
    - name: gnmi
      port: 50051
      protocol: TCP
      targetPort: 50051
  selector:
    role: controller
  type: NodePort

{{- end }}
{{- end }}
