apiVersion: batch/v1
kind: Job
metadata:
  name: delay-job
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: sleep
        image: busybox
        command: ["sh", "-c", "echo 'Delaying pod deployment...' && sleep 10"]
