{{- $root := . }}

{{- $frroutingDefaultImg := "quay.io/frrouting/frr:8.4.7" }}
{{- $frroutingDefaultMemory := "512Mi" }}
{{- $frroutingDefaultCpu := "500m" }}

{{- $networkTypeMap := include "netclab.networkTypeMap" $root | fromYaml }}

{{- range $i, $node := .Values.topology.nodes }}
{{- $nodeName := .name }}
{{- if eq .type "frrouting" }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .name }}
  annotations:
    k8s.v1.cni.cncf.io/networks: {{ include "netclab.nodeNetworks" (dict "node" $node "networkTypeMap" $networkTypeMap "root" $root) }}
  labels:
    vendor: frrouting
    {{- include "netclab.labels" $root | nindent 4 }}
    {{ $root.Chart.Name }}/pod-name: {{ .name }}
spec:
  terminationGracePeriodSeconds: 0
  affinity:
  {{- include "netclab.podAffinity" $root | nindent 4 }}
  containers:
  - name: {{ .name }}
    image: {{ default $frroutingDefaultImg .image }}
    args:
    - sh
    - -c
    - sleep inf
    securityContext:
      privileged: true
      runAsUser: 0
      runAsGroup: 0
    resources:
      limits:
        memory: {{ default $frroutingDefaultMemory .memory }}
        cpu: {{ default $frroutingDefaultCpu .cpu }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    vendor: frrouting
    {{- include "netclab.labels" $root | nindent 4 }}
    {{ $root.Chart.Name }}/pod-name: {{ .name }}
  name: {{ .name }}
spec:
  selector:
    vendor: frrouting
    {{- include "netclab.labels" $root | nindent 4 }}
    {{ $root.Chart.Name }}/pod-name: {{ .name }}
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22

{{- end }}
{{- end }}
