{{- $root := . }}

{{- $linuxDefaultImg := "bash:latest" }}
{{- $linuxDefaultMemory := "200Mi" }}
{{- $linuxDefaultCpu := "200m" }}

{{- $networkTypeMap := include "netclab.networkTypeMap" $root | fromYaml }}

{{- range $i, $node := .Values.topology.nodes }}
{{- $nodeName := .name }}
{{- if eq .type "linux" }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .name }}
  labels:
  {{- include "netclab.labels" $root | nindent 4 }}
  annotations:
    v1.multus-cni.io/default-network: {{ printf "%s-%s" $root.Release.Name $root.Values.topology.default_network.name }}
    k8s.v1.cni.cncf.io/networks: {{ include "netclab.nodeNetworks" (dict "node" $node "networkTypeMap" $networkTypeMap "root" $root) }}
spec:
  terminationGracePeriodSeconds: 0
  affinity:
  {{- include "netclab.podAffinity" $root | nindent 4 }}
  containers:
  - image: {{ default $linuxDefaultImg .image }}
    name: {{ .name }}
    args:
    - sh
    - -c
    - sleep inf
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    resources:
      limits:
        cpu: {{ default $linuxDefaultCpu .cpu }}
        memory: {{ default $linuxDefaultMemory .memory }}

{{- end }}
{{- end }}
