{{- $root := . }}
{{- if eq (include "netclab.hasVeth" .) "true" }}

{{- $networkTypeMap := include "netclab.networkTypeMap" $root | fromYaml }}

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netclab-cleanup
  namespace: kube-system
  labels:
    app: netclab-cleanup
    {{- include "netclab.labels" $root | nindent 4 }}
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-weight: "-5"
spec:
  selector:
    matchLabels:
      app: netclab-cleanup
  template:
    metadata:
      labels:
        app: netclab-cleanup
    spec:
      terminationGracePeriodSeconds: 0
      hostNetwork: true
      hostPID: true
      containers:
      - name: cleanup-veth
        image: alpine:3.20
        securityContext:
          privileged: true
        command:
        - /bin/sh
        - -c
        - |
          set -eux

        {{- range $network := $root.Values.topology.networks }}
        {{- if eq (index $networkTypeMap $network.name) "veth" }}
        {{- $nodesWithVethpair := list }}
        
        {{- range $node := $root.Values.topology.nodes }}
        {{- range $iface := .interfaces }}
        {{- if eq $iface.network $network.name }}

        {{- $nodesWithVethpair = append $nodesWithVethpair $node.name }}

        {{- end }}
        {{- end }}
        {{- end }}

        {{- if eq (len $nodesWithVethpair) 2 }}
          {{- $vethA := printf "%s-%s-%s" $root.Release.Name $network.name (index $nodesWithVethpair 0) }}
          {{- $vethB := printf "%s-%s-%s" $root.Release.Name $network.name (index $nodesWithVethpair 1) }}
          if ip link show {{ $vethA }} >/dev/null 2>&1; then
            ip link del {{ $vethA }}
          fi
          if ip link show {{ $vethB }} >/dev/null 2>&1; then
            ip link del {{ $vethB }}
          fi
        {{- end }}

        {{- else }}
          {{- $bridge :=  printf "%s-%s" $root.Release.Name $network.name }}
          if ip link show {{ $bridge }} >/dev/null 2>&1; then
            ip link del {{ $bridge }}
          fi
        {{- end }}

        {{- end }}

        {{- $defaultBridge := printf "%s-%s" $root.Release.Name $root.Values.topology.default_network.name }}
          if ip link show {{ $defaultBridge }} >/dev/null 2>&1; then
            ip link del {{ $defaultBridge }}
          fi

          sleep infinity  # keep pod alive to prevent restart
      tolerations:
        - operator: Exists
      nodeSelector:
        kubernetes.io/os: linux

{{- end }}
