{{- $root := . }}
{{- range .Values.topology.networks }}
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .name }}
  labels:
{{ include "netclab.labels" $root | indent 4 }}
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "{{ .name }}",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "{{ .name }}",
          "ipam": {}
        }
      ]
    }'
{{- end }}
