{{- $root := . }}

{{- $sonicDefaultImg := "docker.io/mbakalarski/sonic-vs:202505" }}
{{- $sonicDefaultMemory := "2Gi" }}
{{- $sonicDefaultCpu := "2000m" }}

{{- $networkTypeMap := include "netclab.networkTypeMap" $root | fromYaml }}

{{- range $i, $node := .Values.topology.nodes }}
{{- $nodeName := .name }}
{{- if eq .type "sonic" }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .name }}
  labels:
    vendor: sonic
    {{- include "netclab.labels" $root | nindent 4 }}
  annotations:
    v1.multus-cni.io/default-network: {{ $root.Values.topology.default_network.name }}
    k8s.v1.cni.cncf.io/networks: {{ include "netclab.nodeNetworks" (dict "node" $node "networkTypeMap" $networkTypeMap) }}
spec:
  terminationGracePeriodSeconds: 0
  affinity:
  {{- include "netclab.podAffinity" $root | nindent 4 }}
  containers:
  - name: {{ .name }}
    image: {{ default $sonicDefaultImg .image }}
    securityContext:
      privileged: true
      runAsUser: 0
      runAsGroup: 0
    resources:
      limits:
        cpu: {{ default $sonicDefaultCpu .cpu }}
        memory: {{ default $sonicDefaultMemory .memory }}

{{- end }}
{{- end }}
