{{- $root := . }}

{{- $srlinuxDefaultImg := "ghcr.io/nokia/srlinux:latest" }}
{{- $srlinuxDefaultMemory := "4Gi" }}
{{- $srlinuxDefaultCpu := "2000m" }}

{{- $networkTypeMap := include "netclab.networkTypeMap" $root | fromYaml }}

{{- range $i, $node := .Values.topology.nodes }}
{{- $nodeName := .name }}
{{- if eq .type "srlinux" }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .name }}
  annotations:
    v1.multus-cni.io/default-network: {{ $root.Values.topology.default_network.name }}
    k8s.v1.cni.cncf.io/networks: {{ include "netclab.nodeNetworks" (dict "node" $node "networkTypeMap" $networkTypeMap) }}
  labels:
    vendor: nokia
    {{- include "netclab.labels" $root | nindent 4 }}
spec:
  terminationGracePeriodSeconds: 0
  affinity:
  {{- include "netclab.podAffinity" $root | nindent 4 }}
  containers:
  - name: {{ .name }}
    image: {{ default $srlinuxDefaultImg .image }}
    command:
    - /tini
    - --
    - fixuid
    - -q
    - /entrypoint.sh
    args:
    - sudo
    - bash
    - -c
    - /opt/srlinux/bin/sr_linux
    securityContext:
      privileged: true
      runAsUser: 0
      runAsGroup: 0
    resources:
      limits:
        memory: {{ default $srlinuxDefaultMemory .memory }}
        cpu: {{ default $srlinuxDefaultCpu .cpu }}
    volumeMounts:
      - mountPath: /tmp/topology.yml
        subPath: topology.yml
        name: hw
        readOnly: true
  volumes:
  - name: hw
    configMap:
      name: {{ .name }}-hw
      defaultMode: 292
      optional: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-hw
  labels:
    vendor: nokia
    {{- include "netclab.labels" $root | nindent 4 }}
data:
  topology.yml: |-
    # ixrd2
    chassis_configuration:
      "chassis_type": 65
      "base_mac": 00:01:{{ printf "%02x" $i }}:00:00:00
      "cpm_card_type": 176

    slot_configuration:
      1:
        "card_type": 176
        "mda_type": 195

{{- end }}
{{- end }}
