name: netclab-chart

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  deploy-test:
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Install prerequisites
      run: bash .github/workflows/preflight.sh

    - name: Install netclab-chart
      run: |
        cat <<EOF > values.yaml
        topology:
          default_network:
            name: b0
            subnet: 10.10.0.0/24
            gateway: 10.10.0.254
          networks:
          - name: b1
          nodes:
          - name: srl01
            type: srlinux
            memory: 2Gi
            cpu: 500m
            interfaces:
            - name: e1-1
              network: b1
        EOF
        helm upgrade --install netclab . --values values.yaml
